# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe # needed for parsing CFN
      - id: end-of-file-fixer
        exclude: .*\.json-result
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore|
            \.vscode/dictionaries/.*\.txt
          )$
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--implicit_start, --mapping, '2', --offset, '2', --sequence, '4']
        files: |
          (?x)^(
            \.github/(?!dependabot).*\.(yaml|yml)|
            \.markdownlint.yml|
            \.pre-commit-config.yaml|
            \.readthedocs.yml
          )$
  # security
  - repo: https://github.com/awslabs/git-secrets
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
  - repo: https://github.com/lirantal/anti-trojan-source
    rev: v1.4.0
    hooks:
      - id: anti-trojan-source
        exclude: docs/diagrams/.*\.(png)$
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
          - mdformat-config
  - repo: local
    hooks:
      - id: git-diff
        name: git diff
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
